version: '3.8'

services:
  # Vector DB Service
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  vector-server:
    build:
      context: ./rajalakshmi-vector-service
    depends_on:
      - qdrant
    env_file:
      environment:
        QDRANT_URL: ${QDRANT_URL}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        OPENAI_BASE_URL: ${OPENAI_BASE_URL}
        OPENAI_MODEL: ${OPENAI_MODEL}
        SKIP_OPENAI_API_KEY_CHECK: ${SKIP_OPENAI_API_KEY}
    ports:
      - "8000:8000"

  # Website CMS
  mongodb:
    image: mongo:7-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: rajalakshmi_cms
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  cms-app:
    build:
      context: ./rajalakshmi-website-cms
    environment:
    NODE_ENV: ${NODE_ENV}
    DATABASE_URI: ${DATABASE_URI}
    PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    ADMIN_EMAIL: ${ADMIN_EMAIL}
    ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "3001:3000"
    volumes:
      - media_uploads:/usr/src/app/media
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  # AI Chat Service
  ai-chat-server:
    build:
      context: ./rec-ai-chat
    environment:
    NODE_ENV: ${NODE_ENV}
    ports:
      - "3002:3002"

  # Website Chat Service
  website-chat-server:
    build:
      context: ./rajalakshmi-website-chat-service
    ports:
      - "8001:8001"

  # Rajalakshmi Website (Next.js)
  website:
    build:
      context: ./rajalakshmi-website
    env_file:
      environment:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
    ports:
      - "3000:3000"

volumes:
  qdrant_storage:
  mongodb_data:
  media_uploads:
