import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import EllipseBg from "@/components/icons/EllipseBg";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home | Rajalakshmi Engineering College",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}><div className="dotted-vertical-line z-0 fixed left-0 top-0 bottom-0 hidden md:block" />
        <div className="dotted-vertical-line z-0 fixed right-0 top-0 bottom-0 hidden md:block" />
        <div className="min-h-screen font-sans relative overflow-x-hidden z-10">
          <Header />
          <div className="pointer-events-none absolute inset-0 w-full h-full z-50 overflow-hidden hidden md:block">
            <EllipseBg className="absolute left-[-10vw] top-[-10vh] w-[40vw] h-[90vh]" />
            <EllipseBg className="absolute left-[20vw] top-[10vh] w-[40vw] h-[90vh]" />
            <EllipseBg className="absolute left-[50vw] top-[-5vh] w-[40vw] h-[90vh]" />
            <EllipseBg className="absolute left-[70vw] top-[15vh] w-[40vw] h-[90vh]" />
          </div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
